/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuyerRouteImport } from './routes/buyer'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiPublishPreviewRouteImport } from './routes/api.publish-preview'
import { Route as ApiQuoteRouteImport } from './routes/api.quote'
import { Route as ApiSettleRouteImport } from './routes/api.settle'
import { Route as SkillNameRouteImport } from './routes/skill.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerRoute = BuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublishPreviewRoute = ApiPublishPreviewRouteImport.update({
  id: '/api/publish-preview',
  path: '/api/publish-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteRoute = ApiQuoteRouteImport.update({
  id: '/api/quote',
  path: '/api/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettleRoute = ApiSettleRouteImport.update({
  id: '/api/settle',
  path: '/api/settle',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillNameRoute = SkillNameRouteImport.update({
  id: '/skill/$name',
  path: '/skill/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buyer': typeof BuyerRoute
  '/chat': typeof ChatRoute
  '/publish': typeof PublishRoute
  '/seller': typeof SellerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/publish-preview': typeof ApiPublishPreviewRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/settle': typeof ApiSettleRoute
  '/skill/$name': typeof SkillNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buyer': typeof BuyerRoute
  '/chat': typeof ChatRoute
  '/publish': typeof PublishRoute
  '/seller': typeof SellerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/publish-preview': typeof ApiPublishPreviewRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/settle': typeof ApiSettleRoute
  '/skill/$name': typeof SkillNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buyer': typeof BuyerRoute
  '/chat': typeof ChatRoute
  '/publish': typeof PublishRoute
  '/seller': typeof SellerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/publish-preview': typeof ApiPublishPreviewRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/settle': typeof ApiSettleRoute
  '/skill/$name': typeof SkillNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buyer'
    | '/chat'
    | '/publish'
    | '/seller'
    | '/api/chat'
    | '/api/publish-preview'
    | '/api/quote'
    | '/api/settle'
    | '/skill/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buyer'
    | '/chat'
    | '/publish'
    | '/seller'
    | '/api/chat'
    | '/api/publish-preview'
    | '/api/quote'
    | '/api/settle'
    | '/skill/$name'
  id:
    | '__root__'
    | '/'
    | '/buyer'
    | '/chat'
    | '/publish'
    | '/seller'
    | '/api/chat'
    | '/api/publish-preview'
    | '/api/quote'
    | '/api/settle'
    | '/skill/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyerRoute: typeof BuyerRoute
  ChatRoute: typeof ChatRoute
  PublishRoute: typeof PublishRoute
  SellerRoute: typeof SellerRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublishPreviewRoute: typeof ApiPublishPreviewRoute
  ApiQuoteRoute: typeof ApiQuoteRoute
  ApiSettleRoute: typeof ApiSettleRoute
  SkillNameRoute: typeof SkillNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer': {
      id: '/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof BuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publish-preview': {
      id: '/api/publish-preview'
      path: '/api/publish-preview'
      fullPath: '/api/publish-preview'
      preLoaderRoute: typeof ApiPublishPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote': {
      id: '/api/quote'
      path: '/api/quote'
      fullPath: '/api/quote'
      preLoaderRoute: typeof ApiQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settle': {
      id: '/api/settle'
      path: '/api/settle'
      fullPath: '/api/settle'
      preLoaderRoute: typeof ApiSettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill/$name': {
      id: '/skill/$name'
      path: '/skill/$name'
      fullPath: '/skill/$name'
      preLoaderRoute: typeof SkillNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyerRoute: BuyerRoute,
  ChatRoute: ChatRoute,
  PublishRoute: PublishRoute,
  SellerRoute: SellerRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublishPreviewRoute: ApiPublishPreviewRoute,
  ApiQuoteRoute: ApiQuoteRoute,
  ApiSettleRoute: ApiSettleRoute,
  SkillNameRoute: SkillNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
